# Generated by Django 3.1 on 2023-06-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='permission',
        ),
    ]
